### ISSUE TITLE
The interface looks awful

### ISSUE THREAD

**Issue by tiggerbiggo** [tiggerbiggo/Prima#10]
Terribly laid out buttons, this should be easy enough to fix since fxml is a thing, but having a better button layout will help new users find their way around

**Comment by Shiny0** [comment]
Change that window title

**Comment by I-Al-Istannen** [comment]
Maybe follow some design guideline like Material Design or whatever you dig out? For the latter JPhoenix provides a nice set of controls.

And then change the color of cards to match the style scheme, maybe round the edges and give it some depth via a shadow.
